import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { getSupabaseServiceClient } from '@/lib/supabase/server'
import { buildClickUpClient } from '@/lib/clickup/client'
import { writeVaultFile, createVaultBranch } from '@/lib/github/vault'
import { computeFullFVI } from '@/lib/fvi'
import type { RoleAssessment, ObjectiveScore } from '@/lib/fvi'
import type { Json } from '@/lib/supabase/types'

type Params = { params: Promise<{ id: string; conversationId: string }> }

// ── Bundle content generators ─────────────────────────────────────────────────

function buildKickoffPrompt(
  taskName: string,
  clickupTaskId: string,
  fvi: ReturnType<typeof computeFullFVI>,
  effort: number,
  risk: number
): string {
  return `# Kickoff Prompt — ${taskName}

> Posted by PM Agent on FVI assessment approval. Use this as your opening message when starting a Claude session on this feature.

**ClickUp Task:** ${clickupTaskId}
**FVI Score:** ${fvi.fviScore} — ${fvi.decision.replace(/-/g, ' ')}
**Effort:** ${effort} dev-day${effort !== 1 ? 's' : ''} | **Risk multiplier:** ${risk}x
**Trojan Horse flag:** ${fvi.trojanHorse ? '⚠️ YES — review objective scores before proceeding' : 'No'}

## Your Mission

You are a developer starting work on **${taskName}**. The vault spec, roles-affected, and plan-draft files are in this branch. Your first actions:

1. Read \`spec.md\` for the full feature context and acceptance criteria.
2. Read \`roles-affected.md\` to understand whose workflows this touches.
3. Read \`plan-draft.md\` and fill in the Engineering Plan before moving to Architecting.
4. Confirm the Kickoff Checklist in the Sprint Planner is fully green before writing code.

## FVI Context

| Objective Total | Inverted Influence | Decision |
|----------------|-------------------|----------|
| ${fvi.objTotal} / 70 | ${fvi.invertedInfluence.toFixed(3)} | ${fvi.decision} |
`
}

function buildRolesAffected(
  taskName: string,
  roles: Array<{ roleName: string; teamDomain?: string; influenceType: string; weight: number; usageFrequency: number }>,
  fvi: ReturnType<typeof computeFullFVI>
): string {
  const freq = (f: number) => ['', 'Access Default', 'Access Sometimes', 'Uses Sometimes', 'Uses Every Day'][f] ?? String(f)
  const dmRoles = roles.filter((r) => r.influenceType === 'DM')
  const ndmRoles = roles.filter((r) => r.influenceType === 'NDM')

  const table = (list: typeof roles) =>
    list.length === 0
      ? '_None_\n'
      : `| Role | Team | Weight | Usage | Score |\n|------|------|--------|-------|-------|\n` +
        list.map((r) => `| ${r.roleName} | ${r.teamDomain ?? '—'} | ${r.weight} | ${freq(r.usageFrequency)} | ${r.weight * r.usageFrequency} |`).join('\n') + '\n'

  return `# Roles Affected — ${taskName}

## Decision-Maker Roles (DM)

${table(dmRoles)}
## Non-Decision-Maker Roles (NDM)

${table(ndmRoles)}
## FVI Influence Summary

| I_DM (norm) | I_NDM (norm) | Inverted Influence |
|-------------|--------------|-------------------|
| ${fvi.iDmNorm.toFixed(3)} | ${fvi.iNdmNorm.toFixed(3)} | ${fvi.invertedInfluence.toFixed(3)} |
`
}

function buildPlanDraft(
  taskName: string,
  fvi: ReturnType<typeof computeFullFVI>,
  effort: number,
  risk: number
): string {
  return `# Plan Draft — ${taskName}

> Stub generated by PM Agent at FVI assessment. Complete the Engineering Plan sections during the Architecting phase before moving this task to Architecting status in ClickUp.

**FVI:** ${fvi.fviScore} | **Decision:** ${fvi.decision}
**Effort:** ${effort} dev-day${effort !== 1 ? 's' : ''} | **Risk:** ${risk}x

---

## Problem Statement

_What problem does this solve? Who experiences it?_

## Proposed Solution

_High-level approach. What changes, what stays the same._

## Engineering Plan

_Populated during Architecting. List the files, APIs, and DB changes._

## Acceptance Criteria

_Pulled from spec.md — confirm they are still accurate before coding starts._

## Open Questions

_List any blockers or unknowns that need resolution before implementation._
`
}

function buildClaudeMdBlock(
  taskName: string,
  clickupTaskId: string,
  vaultBranch: string,
  fvi: ReturnType<typeof computeFullFVI>,
  roles: Array<{ roleName: string; teamDomain?: string; influenceType: string; weight: number; usageFrequency: number }>
): string {
  // Top 3 DM roles by score — these are the user-perspective SKILLs gate #2 requires
  const topDmRoles = roles
    .filter((r) => r.influenceType === 'DM')
    .sort((a, b) => b.weight * b.usageFrequency - a.weight * a.usageFrequency)
    .slice(0, 3)

  const skillLines = topDmRoles.length > 0
    ? topDmRoles.map((r) => {
        const slug = r.roleName.toLowerCase().replace(/\s+/g, '-')
        return `- \`documentation/AI Tools/Skills/user-perspective/${slug}.md\` (${r.roleName}, score: ${r.weight * r.usageFrequency})`
      }).join('\n')
    : '- _(No DM roles identified — check roles-affected.md)_'

  return `<!-- CLAUDE.md injection for: ${taskName} -->
<!-- Remove this block when task reaches Deployed status -->

## Active Feature Context

**Feature:** ${taskName}
**ClickUp:** ${clickupTaskId}
**Vault branch:** \`${vaultBranch}\`
**FVI:** ${fvi.fviScore} (${fvi.decision})${fvi.trojanHorse ? '\n**⚠️ Trojan Horse flag is set — high data value but low modularity/user-success scores. Proceed with caution.**' : ''}

### Vault Files (read before coding)

- \`spec.md\` — acceptance criteria and feature context
- \`roles-affected.md\` — whose workflows this touches
- \`plan-draft.md\` — engineering plan (fill in during Architecting)
- \`kickoff-prompt.md\` — your session opening context

### User-Perspective SKILLs (Kickoff Checklist gate #2)

Load these before drafting user stories or acceptance criteria:

${skillLines}

### Figma (Kickoff Checklist gate #3)

The Figma Selection Link is embedded in \`spec.md\` by the PM Agent when the designer shares a component link during the Architecting phase. **Do not proceed to Architecting status until that link is present in spec.md.** If you cannot find it, ask the PM to run the Architecting trigger before you continue.

### Focus Constraints

- Scope every change to this feature only. Do not refactor unrelated code.
- If a change would touch auth, billing, or permissions, stop and flag it.
- All new files go in the branch — do not merge to main until ROI is validated.
- Run tests before marking any task as Ready for QA.
<!-- END CLAUDE.md injection -->
`
}

// POST /api/sprint/tasks/[id]/assess/[conversationId]/confirm
// Final step: user has confirmed scores, roles, effort, risk.
// Computes FVI, saves everything, writes vault spec, updates ClickUp.
export async function POST(req: NextRequest, { params }: Params) {
  const { id, conversationId } = await params
  const session = await auth()
  if (!session?.user?.email) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json()
  const {
    scores,       // Array<{ objectiveId, score, objectiveName, objectiveOwner, reasoning }>
    roles,        // Array<{ roleId, roleName, influenceType, weight, usageFrequency }>
    effort,       // number (total dev-days)
    risk,         // number (1.0, 1.2, 1.5, 2.0, 3.0)
    updatedDescription, // string | null — updated task description from Claude
    vaultSpecContent,   // string | null — vault spec stub markdown
  } = body

  const supabase = await getSupabaseServiceClient()

  const { data: user } = await supabase.from('users').select('id').eq('email', session.user.email).single()
  if (!user) return NextResponse.json({ error: 'User not found' }, { status: 404 })

  const { data: conv } = await supabase
    .from('assessment_conversations')
    .select('id, task_id')
    .eq('id', conversationId)
    .eq('task_id', id)
    .single()
  if (!conv) return NextResponse.json({ error: 'Conversation not found' }, { status: 404 })

  const { data: task } = await supabase
    .from('tasks')
    .select('id, clickup_task_id, name')
    .eq('id', id)
    .single()
  if (!task) return NextResponse.json({ error: 'Task not found' }, { status: 404 })

  // ── Compute FVI ─────────────────────────────────────────────────────────────
  const objectiveScores: ObjectiveScore[] = scores.map((s: { objectiveId: number; score: number }) => ({
    objectiveId: s.objectiveId,
    score: s.score,
  }))

  const roleAssessments: RoleAssessment[] = roles.map((r: { roleName: string; influenceType: string; weight: number; usageFrequency: number }) => ({
    roleName: r.roleName,
    influenceType: r.influenceType as 'DM' | 'NDM',
    weight: r.weight,
    usageFrequency: r.usageFrequency,
  }))

  const fviResult = computeFullFVI(objectiveScores, roleAssessments, effort, risk)

  // ── Save objective_assessments ──────────────────────────────────────────────
  await Promise.all(
    scores.map((s: { objectiveId: number; score: number; reasoning?: string }) =>
      supabase.from('objective_assessments').upsert(
        { task_id: id, objective_id: s.objectiveId, score: s.score, reasoning: s.reasoning ?? null },
        { onConflict: 'task_id,objective_id' }
      )
    )
  )

  // ── Save conversation role assessments ──────────────────────────────────────
  // Lookup role IDs
  const { data: roleRows } = await supabase.from('role_registry').select('id, role_name, team_domain')
  const roleIdMap = new Map((roleRows ?? []).map((r) => [`${r.role_name}::${r.team_domain}`, r.id]))

  await Promise.all(
    roles.map((r: { roleName: string; teamDomain: string; usageFrequency: number }) => {
      const roleId = roleIdMap.get(`${r.roleName}::${r.teamDomain}`)
      if (!roleId) return Promise.resolve()
      return supabase.from('conversation_role_assessments').insert({
        conversation_id: conversationId,
        role_id: roleId,
        usage_frequency: r.usageFrequency,
      })
    })
  )

  // ── Update tasks table ──────────────────────────────────────────────────────
  await supabase.from('tasks').update({
    fvi_score: fviResult.fviScore,
    cost_effort: effort,
    cost_risk: risk,
    inverted_influence: Math.round(fviResult.invertedInfluence * 1000) / 1000,
  }).eq('id', id)

  // ── Update assessment_conversations ────────────────────────────────────────
  await supabase.from('assessment_conversations').update({
    status: 'complete',
    final_scores: scores as unknown as Json,
    effort,
    risk,
    fvi_score: fviResult.fviScore,
    completed_at: new Date().toISOString(),
  }).eq('id', conversationId)

  // ── Fetch external tokens once ────────────────────────────────────────────
  const [{ data: cuToken }, { data: ghToken }] = await Promise.all([
    supabase.from('oauth_tokens').select('access_token').eq('user_id', user.id).eq('provider', 'clickup').single(),
    supabase.from('oauth_tokens').select('access_token').eq('user_id', user.id).eq('provider', 'github').single(),
  ])

  // ── ClickUp description write-back (non-fatal) ─────────────────────────────
  if (updatedDescription && cuToken?.access_token) {
    try {
      const cu = buildClickUpClient(cuToken.access_token)
      await cu.updateTask(task.clickup_task_id, { description: updatedDescription })
    } catch (err) {
      console.error(`[assess:confirm task=${id}] ClickUp description update failed:`, err)
    }
  }

  // ── Vault Resource Bundle write-back (non-fatal) ───────────────────────────
  // Atomicity contract: git_branch is only persisted if spec.md commits successfully.
  // Secondary files (roles-affected, kickoff-prompt, plan-draft) are each non-fatal.
  let vaultSpecUrl: string | null = null
  let vaultBranch: string | null = null

  if (vaultSpecContent && ghToken?.access_token) {
    try {
      const slug = task.name.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim().replace(/\s+/g, '-').slice(0, 40)
      const dir = `FeaturePlanning/_Active/${task.clickup_task_id}-${slug}`
      const today = new Date().toISOString().slice(0, 10)
      const commitMsg = (file: string) => `PM Agent: ${file} for ${task.name} (${today})`

      // 1. Ensure feature branch exists
      vaultBranch = await createVaultBranch(ghToken.access_token, task.clickup_task_id, task.name)

      // 2. Write spec.md — gating write. If this throws, git_branch is NOT saved.
      const written = await writeVaultFile(ghToken.access_token, `${dir}/spec.md`, vaultSpecContent, commitMsg('FVI assessment'), vaultBranch)
      if (!written) throw new Error('spec.md write returned null')
      vaultSpecUrl = written.url

      // 3. Persist branch name — spec is confirmed on the branch
      await supabase.from('tasks').update({ git_branch: vaultBranch }).eq('id', id)

      // 4. Secondary bundle files — each non-fatal
      const kickoffContent = buildKickoffPrompt(task.name, task.clickup_task_id, fviResult, effort, risk)
      await writeVaultFile(ghToken.access_token, `${dir}/kickoff-prompt.md`, kickoffContent, commitMsg('kickoff prompt'), vaultBranch).catch((err) => console.error(`[assess:confirm task=${id}] kickoff-prompt.md write failed:`, err))
      await writeVaultFile(ghToken.access_token, `${dir}/roles-affected.md`, buildRolesAffected(task.name, roles, fviResult), commitMsg('roles affected'), vaultBranch).catch((err) => console.error(`[assess:confirm task=${id}] roles-affected.md write failed:`, err))
      await writeVaultFile(ghToken.access_token, `${dir}/plan-draft.md`, buildPlanDraft(task.name, fviResult, effort, risk), commitMsg('plan draft stub'), vaultBranch).catch((err) => console.error(`[assess:confirm task=${id}] plan-draft.md write failed:`, err))
      await writeVaultFile(ghToken.access_token, `${dir}/claude-md-block.md`, buildClaudeMdBlock(task.name, task.clickup_task_id, vaultBranch, fviResult, roles), commitMsg('CLAUDE.md injection block'), vaultBranch).catch((err) => console.error(`[assess:confirm task=${id}] claude-md-block.md write failed:`, err))

      // 5. ClickUp comment — kickoff prompt is the developer's zero-friction entry point
      if (cuToken?.access_token) {
        try {
          const cu = buildClickUpClient(cuToken.access_token)
          await cu.createTaskComment(task.clickup_task_id, kickoffContent)
        } catch (err) {
          console.error(`[assess:confirm task=${id}] ClickUp kickoff comment failed:`, err)
        }
      }
    } catch (err) {
      // spec write failed — branch may exist but has no Resource Bundle; do not surface gate #1 as green
      console.error(`[assess:confirm task=${id}] spec.md gating write failed — git_branch will not be saved:`, err)
      vaultBranch = null
    }
  }

  return NextResponse.json({
    fviScore: fviResult.fviScore,
    decision: fviResult.decision,
    objTotal: fviResult.objTotal,
    invertedInfluence: fviResult.invertedInfluence,
    iDmNorm: fviResult.iDmNorm,
    iNdmNorm: fviResult.iNdmNorm,
    trojanHorse: fviResult.trojanHorse,
    effort,
    risk,
    vaultBranch,
    vaultSpecUrl,
  })
}
