-- Migration 006: Design Review
--
-- Changes:
--   assessment_conversations — add design_review JSONB column
--     Persists the guided tour + divergence notes generated by /design-review.
--     Enables idempotency: /design-review returns cached result on re-call.
--
-- Safe to re-run — uses ADD COLUMN IF NOT EXISTS.

ALTER TABLE assessment_conversations
  ADD COLUMN IF NOT EXISTS design_review JSONB;

COMMENT ON COLUMN assessment_conversations.design_review IS
  'Cached output of POST /design-review: { steps, divergenceNotes, figmaFrames, warnings, generatedAt }. '
  'Populated once after /confirm. Route returns cached result on subsequent calls (cached: true).';